### ISSUE TITLE
Garum 0.1.1 on Maven is not correct.

### ISSUE THREAD

**Issue by yhirano** [operando/Garum#10]
Maybe Garum 0.1.1 on Maven is not correct.
It seem that source codes of http://repo1.maven.org/maven2/com/github/operando/garum/0.1.0/garum-0.1.0-sources.jar and http://repo1.maven.org/maven2/com/github/operando/garum/0.1.0/garum-0.1.1-sources.jar is same.

```console
% curl -O http://repo1.maven.org/maven2/com/github/operando/garum/0.1.0/garum-0.1.0-sources.jar
% curl -O http://repo1.maven.org/maven2/com/github/operando/garum/0.1.1/garum-0.1.1-sources.jar
% unzip garum-0.1.0-sources.jar -d garum-0.1.0-sources
% unzip garum-0.1.1-sources.jar -d garum-0.1.1-sources
% diff -rq garum-0.1.0-sources/com garum-0.1.1-sources/com
Only in garum-0.1.0-sources/com: .DS_Store
Only in garum-0.1.0-sources/com/os: .DS_Store
Only in garum-0.1.0-sources/com/os/operando: .DS_Store
Only in garum-0.1.0-sources/com/os/operando/garum: .DS_Store
```

Please confirm the above.

**Comment by operando** [comment]
Sorry!!
Reupload Garum 0.1.1 to Maven Central.
Try again to clean the environment.

**Comment by yhirano** [comment]
👍 

It was confirmed that the PrefModel#clear method issue is fixed on a Maven binary.

**Comment by yhirano** [comment]
I confirmed that the binary updated on MavenCentral, but doesn't updated on jcenter...

https://bintray.com/bintray/jcenter/com.github.operando%3Agarum/0.1.1/view#files/com/github/operando/garum/0.1.1
