### ISSUE TITLE
Configuration.BuilderのsetModelClassesでwarningが出る

### ISSUE THREAD

**Issue by Innsbluck-Redhat** [operando/Garum#11]
Android Studio 2.2.3を使用しています。
ActivityのonCreate内で
```
Context context = getApplicationContext();
Configuration.Builder builder = new Configuration.Builder(context);
builder.setModelClasses(LoginPref.class);
Garum.initialize(builder.create());
```
とすると、Android Studioから
Unchecked generics array creation for varargs parameter
というwarningが出ます。

**Comment by operando** [comment]
:eyes:

**Comment by operando** [comment]
Thanks, report issue.

Fixed https://github.com/operando/Garum/pull/12.
